refact(margins): replace descriptors by new objects
Mypy has a bug that raises an error when attempting to override read-only
descriptors with read-only properties:

```
pandora2d/interpolation_filter/bicubic_cpp.py:51: error: Cannot override writeable attribute with read-only property  [override]
pandora2d/interpolation_filter/bicubic_cpp.py:51: error: Signature of "margins" incompatible with supertype "AbstractFilter"  [override]
pandora2d/interpolation_filter/bicubic_cpp.py:51: note:      Superclass:
pandora2d/interpolation_filter/bicubic_cpp.py:51: note:          NullMargins
pandora2d/interpolation_filter/bicubic_cpp.py:51: note:      Subclass:
pandora2d/interpolation_filter/bicubic_cpp.py:51: note:          Margins
```

Since descriptors were underused, we decided to stop using them in favor of
properties. To avoid modifying Pandora's code, we added new margin types in
Pandora2D: `UniformMargins` and `NullMargins`, which are subclasses of
`Margins` instead of descriptors, as they were in Pandora.

To enable equality checks between `Margins` and these new margin types, I had
to extend Pandora's `Margins` with a `__eq__` method and update all imports
to reference `Margins` from `Pandora2D` instead of `Pandora`.

Some import orders also had to be changed to satisfy Pylint.