chore: add option to mypy to workaround bug with map
This is the error encountred:

```
pandora2d/state_machine.py:259: error: Argument 1 to "map" has incompatible type overloaded function; expected "Callable[[int, int], SupportsRichComparisonT]"  [arg-type]
```

This is where the solution was found:

[github issue comment](https://github.com/python/mypy/issues/9765#issuecomment-1728176821)

It seems that it’s will be the default behavior in mypy 1.7 so it could
be removed then.